export const TOP_NAV_LINKS = [
  { label: 'Dashboard', to: '/servers', end: true },
  { label: 'Docs', to: '/docs', end: true },
  { label: 'Support Server', external: true, href: 'https://discord.gg/qyajpWYHja' },
];

export const SIDEBAR_GROUPS = [
  {
    title: 'Control Center',
    items: [{ key: 'dashboard', label: 'Dashboard', icon: '🏠', path: '/app' }],
  },
  {
    title: 'Modules',
    items: [
      { key: 'guild-economy', label: 'Economy', icon: '💸', path: '/app/guild/economy' },
      { key: 'guild-items', label: 'Items', icon: '🎫', path: '/app/guild/items' },
      { key: 'guild-boxes', label: 'Mystery Boxes', icon: '🎁', path: '/app/guild/boxes' },
      { key: 'guild-market', label: 'Marketplace', icon: '🛍️', path: '/app/guild/marketplace' },
      { key: 'guild-trades', label: 'Trades & Gifts', icon: '🤝', path: '/app/guild/trades' },
      { key: 'guild-auctions', label: 'Auctions', icon: '🏦', path: '/app/guild/auctions' },
      { key: 'guild-raffles', label: 'Raffles', icon: '🎟️', path: '/app/guild/raffles' },
      { key: 'guild-shop', label: 'Server Shop', icon: '🏪', path: '/app/guild/shop' },
      { key: 'guild-leaderboards', label: 'Leaderboards', icon: '🏆', path: '/app/guild/leaderboards' },
    ],
  },
  {
    title: 'System',
    items: [
      { key: 'guild-audit', label: 'Audit Logs', icon: '🛡️', path: '/app/guild/audit' },
      { key: 'guild-billing', label: 'Billing', icon: '💳', path: '/app/guild/billing' },
      { key: 'guild-system', label: 'Server Settings', icon: '⚙️', path: '/app/guild/system' },
    ],
  },
];

export const FEATURE_SECTIONS = [
  { key: 'core', title: 'Core Features', description: 'XP engines, jobs, and marketplaces that drive your economy.' },
  { key: 'management', title: 'Server Management', description: 'Drops, raffles, and hype mechanics for every event.' },
  { key: 'utilities', title: 'Utilities', description: 'Premium tooling, leaderboards, and observability layers.' },
];

export const PRICING_PLANS = [
  {
    id: 'lite',
    name: 'Lite',
    monthly: 2.49,
    monthlyAfter: 4.99,
    yearly: 1.87,
    yearlyAfter: 3.74,
    badge: null,
    features: [
      { label: 'Economy + jobs modules', included: true },
      { label: 'Marketplace + raffles', included: true },
      { label: 'Basic audit logs', included: true },
      { label: 'Premium-only features', included: false },
      { label: 'Concierge support', included: false },
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    monthly: 3.99,
    monthlyAfter: 7.99,
    yearly: 2.99,
    yearlyAfter: 5.99,
    badge: 'Most Popular',
    features: [
      { label: 'Everything in Lite', included: true },
      { label: 'Premium-only features 👑', included: true },
      { label: 'Advanced analytics', included: true },
      { label: 'Concierge support', included: false },
    ],
  },
  {
    id: 'ultra',
    name: 'Ultra',
    monthly: 7.99,
    monthlyAfter: 15.99,
    yearly: 5.99,
    yearlyAfter: 11.99,
    badge: null,
    features: [
      { label: 'Everything in Premium', included: true },
      { label: 'Concierge support', included: true },
      { label: 'Custom branding', included: true },
      { label: '24/7 ops bridge', included: true },
    ],
  },
];

export const PLAN_COMPARISON = [
  { feature: 'Economy + Jobs', tiers: { free: true, lite: true, premium: true, ultra: true } },
  { feature: 'Marketplace + Raffles', tiers: { free: false, lite: true, premium: true, ultra: true } },
  { feature: 'Premium-only commands', tiers: { free: false, lite: false, premium: true, ultra: true } },
  { feature: 'Concierge support', tiers: { free: false, lite: false, premium: false, ultra: true } },
  { feature: 'Custom branding', tiers: { free: false, lite: false, premium: true, ultra: true } },
];

export const COMMAND_GROUPS = [
  {
    title: 'Economy & Transfers',
    description: 'Core balance management commands for your in-server economy.',
    commands: ['/trade', '/gift', '/add-money', '/remove-money', '/balance', '/daily', '/work', '/<currency>-leaderboard'],
  },
  {
    title: 'Items & Inventory',
    description: 'Create, edit, and inspect virtual goods members can equip.',
    commands: ['/create-item', '/edit-item', '/view-item', '/remove-item', '/add-item', '/inventory', '/item-leaderboard'],
  },
  {
    title: 'Shops & Marketplace',
    description: 'Sell goods in user shops or server-wide storefronts.',
    commands: ['/marketplace', '/user-shop', '/serverwide-shop-view', '/serverwide-shop-edit', '/serverwide-shop-buy', '/test-shop'],
  },
  {
    title: 'Auctions & Raffles',
    description: 'High-stakes raffles and live auction house bidding.',
    commands: ['/auction-house-add', '/auction-house-bid', '/auction-house-view', '/create-raffle', '/buy-tickets'],
  },
  {
    title: 'Mystery Boxes & Battles',
    description: 'Hype-driven boxes, battles, and related flows.',
    commands: ['/create-mystery-box', '/edit-mystery-box', '/view-mystery-boxes', '/buy-mystery-box', '/open-mystery-box', '/box-battles'],
  },
  {
    title: 'Announcements',
    description: 'Keep members looped in about drops and events.',
    commands: ['/notifications'],
  },
];

export const FEATURE_MODULES = [
  {
    key: 'economy',
    title: 'Economy Engine',
    description: 'Tune payouts, taxes, and cooldowns to shape your currency loops.',
    icon: '💸',
    category: 'core',
    premium: false,
    route: '/app/economy',
    pill: 'Core',
    defaultEnabled: true,
    modes: ['balanced', 'aggressive', 'chill'],
  },
  {
    key: 'jobs',
    title: 'Jobs Board',
    description: 'Stackable contracts with difficulty tiers, rerolls, and streak logic.',
    icon: '🛠️',
    category: 'core',
    premium: false,
    route: '/app/jobs',
    pill: 'Automation',
    defaultEnabled: true,
    modes: ['standard', 'hardcore', 'cozy'],
  },
  {
    key: 'marketplace',
    title: 'Marketplace',
    description: 'Let members trade cosmetics, boosts, and creator drops safely.',
    icon: '🛍️',
    category: 'core',
    premium: false,
    route: '/app/marketplace',
    pill: 'Commerce',
    defaultEnabled: true,
    modes: ['curated', 'open', 'seasonal'],
  },
  {
    key: 'serverwideStore',
    title: 'Serverwide Store',
    description: 'Curate server-operated storefronts with limited drops and global inventory controls.',
    icon: '🏪',
    category: 'core',
    premium: false,
    route: '/app/marketplace',
    pill: 'Commerce',
    defaultEnabled: true,
    modes: ['standard', 'limited', 'event'],
  },
  {
    key: 'mysteryBoxes',
    title: 'Mystery Boxes',
    description: 'Create fully custom mystery boxes with rewards, rarities, and exciting randomized openings.',
    icon: '🎁',
    category: 'management',
    premium: false,
    route: '/app/mystery-boxes',
    pill: 'Events',
    defaultEnabled: false,
    modes: ['cinematic', 'arcade', 'minimal'],
  },
  {
    key: 'raffles',
    title: 'Raffles',
    description: 'Ticket-based giveaways with verification and multi-winner draws.',
    icon: '🎟️',
    category: 'management',
    premium: false,
    route: '/app/raffles',
    pill: 'Engagement',
    defaultEnabled: true,
    modes: ['verification', 'open'],
  },
  {
    key: 'leaderboards',
    title: 'Leaderboards',
    description: 'Seasonal ranked ladders with trophy roles and automated resets.',
    icon: '🏆',
    category: 'utilities',
    premium: true,
    route: '/app/leaderboards',
    pill: 'Premium',
    defaultEnabled: true,
    modes: ['seasonal', 'lifetime'],
  },
  {
    key: 'premium',
    title: 'Premium Hub',
    description: 'AI insights, concierge support, and branding overrides for top guilds.',
    icon: '💎',
    category: 'utilities',
    premium: true,
    route: '/app/premium',
    pill: 'Upgrade',
    defaultEnabled: true,
    modes: ['ai', 'concierge'],
  },
  {
    key: 'logs',
    title: 'Audit Logs',
    description: 'Live stream of bot actions with retention controls and alerts.',
    icon: '📜',
    category: 'utilities',
    premium: false,
    route: '/app/logs',
    pill: 'Visibility',
    defaultEnabled: true,
    modes: ['compressed', 'verbose'],
  },
  {
    key: 'settings',
    title: 'Server Settings',
    description: 'Maintenance windows, beta access, and timezone alignment.',
    icon: '⚙️',
    category: 'utilities',
    premium: false,
    route: '/app/settings',
    pill: 'Admin',
    defaultEnabled: true,
    modes: ['auto', 'manual'],
  },
];

export const FEATURE_FLAG_DEFAULTS = FEATURE_MODULES.reduce((acc, module) => {
  acc[module.key] = {
    enabled: module.defaultEnabled ?? false,
    mode: module.modes?.[0] ?? 'auto',
  };
  return acc;
}, {});

export const MOCK_GUILDS = [
  {
    id: 'guild-starlance',
    name: 'Starlance Collective',
    icon: '🌌',
    memberCount: 128402,
    premium: true,
    vanity: 'starlance.gg',
  },
  {
    id: 'guild-synth',
    name: 'Synth District',
    icon: '🎛️',
    memberCount: 74218,
    premium: false,
    vanity: 'discord.gg/synth',
  },
  {
    id: 'guild-harbor',
    name: 'Harbor Operators',
    icon: '⚓',
    memberCount: 22451,
    premium: false,
    vanity: 'plixi.gg/harbor',
  },
];

export const DEFAULT_SETTINGS = {
  economy: {
    economyEnabled: true,
    currencyName: 'Credits',
    startingBalance: 250,
    decimalsEnabled: false,
    dailyRewardsEnabled: true,
    dailyBaseAmount: 200,
    dailyRoleRewards: [
      { id: 'role-vip', role: '@VIP', amount: 350 },
      { id: 'role-booster', role: '@Booster', amount: 500 },
    ],
    dailyCooldownHours: 24,
    streaksEnabled: true,
    streakBonusMultiplier: 1.25,
    workEnabled: true,
    workCooldownMinutes: 45,
    workPayMin: 120,
    workPayMax: 320,
  },
  jobs: {
    jobsEnabled: true,
    jobDifficulty: 'standard',
    shiftLength: 4,
    payoutMultiplier: 1.2,
    rerollCost: 150,
    autoAssign: true,
  },
  marketplace: {
    marketplaceEnabled: true,
    allowUserListings: true,
    listingFee: 4,
    featuredSlots: 3,
    currencyName: 'Credits',
    premiumAnalytics: true,
  },
  mysteryBoxes: {
    boxesEnabled: true,
    legendaryRate: 3,
    animationStyle: 'nebula',
    guaranteedDrops: false,
  },
  raffles: {
    rafflesEnabled: true,
    maxTickets: 120,
    requireVerification: true,
    notifyWinners: true,
    autoClaim: false,
  },
  premium: {
    aiInsights: true,
    brandingControl: true,
    concierge: false,
  },
  logs: {
    logRetentionDays: 14,
    streamingChannels: ['#plixi-audit'],
    alertOnFailures: true,
    maskSensitive: true,
  },
  leaderboards: {
    leaderboardsEnabled: true,
    rotation: 'monthly',
    rewardRole: 'Top 10',
    celebrateWithEmbeds: true,
  },
  settings: {
    maintenanceMode: false,
    timezone: 'UTC',
    allowBeta: true,
  },
  guild: {
    currency: {
      name: 'Credits',
      startingBalance: 250,
      decimalsEnabled: false,
      auditLog: { enabled: true, channel: '#currency-audit' },
    },
    daily: {
      enabled: true,
      baseAmount: 200,
      cooldownHours: 24,
      roleAmounts: [
        { id: 'vip', role: '@VIP', amount: 320 },
        { id: 'vip-plus', role: '@VIP+', amount: 450 },
      ],
      streak: {
        enabled: true,
        profile: 'regular',
        multiplier: 1.3,
      },
    },
    work: {
      enabled: true,
      cooldownMinutes: 45,
      cooldownUnit: 'minutes',
      payMin: 120,
      payMax: 320,
      jobs: [
        { id: 'job-1', name: 'Nebula Courier' },
        { id: 'job-2', name: 'Quantum Analyst' },
        { id: 'job-3', name: 'Forge Tech' },
      ],
    },
    items: {
      enabled: true,
      catalog: [
        { id: 'item-1', name: 'Starlance Badge', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 25 },
        { id: 'item-2', name: 'Nebula Cape', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 5 },
        { id: 'item-3', name: 'Photon Aegis', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 40 },
        { id: 'item-4', name: 'Aurora Codex', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 12 },
        { id: 'item-5', name: 'Quantum Relay', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 33 },
        { id: 'item-6', name: 'Pulse Harp', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 4 },
        { id: 'item-7', name: 'Nova Bloom', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 64 },
        { id: 'item-8', name: 'Meteor Loom', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 14 },
        { id: 'item-9', name: 'Prism Idol', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 28 },
        { id: 'item-10', name: 'Atlas Compass', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 80 },
        { id: 'item-11', name: 'Echo Lantern', rarity: 'Common', image: 'https://placehold.co/96x96', stock: 150 },
        { id: 'item-12', name: 'Velvet Circuit', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 42 },
        { id: 'item-13', name: 'Solar Bloom Box', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 6 },
        { id: 'item-14', name: 'Chromatic Anchor', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 18 },
        { id: 'item-15', name: 'Pulse Weave', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 30 },
        { id: 'item-16', name: 'Nebula Sandglass', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 27 },
        { id: 'item-17', name: 'Cypher Cascade', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 16 },
        { id: 'item-18', name: 'Lumen Crown', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 5 },
        { id: 'item-19', name: 'Gale Ribbon', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 75 },
        { id: 'item-20', name: 'Drift Alloy', rarity: 'Common', image: 'https://placehold.co/96x96', stock: 190 },
        { id: 'item-21', name: 'Mythic Token', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 8 },
        { id: 'item-22', name: 'Glacier Prism', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 20 },
        { id: 'item-23', name: 'Cascade Drum', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 38 },
        { id: 'item-24', name: 'Digital Fern', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 96 },
        { id: 'item-25', name: 'Warden Glyph', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 22 },
        { id: 'item-26', name: 'Pulse Echo Band', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 35 },
        { id: 'item-27', name: 'Chrono Kite', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 88 },
        { id: 'item-28', name: 'Zero Bloom', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 70 },
        { id: 'item-29', name: 'Seeker Ledger', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 17 },
        { id: 'item-30', name: 'Flux Pendant', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 40 },
        { id: 'item-31', name: 'Astral Loom', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 3 },
        { id: 'item-32', name: 'Ion Nova Shard', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 32 },
        { id: 'item-33', name: 'Reactor Key', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 14 },
        { id: 'item-34', name: 'Cobalt Feather', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 110 },
        { id: 'item-35', name: 'Lattice Bloom', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 36 },
        { id: 'item-36', name: 'Helix Circuit', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 15 },
        { id: 'item-37', name: 'Pulse Orchard', rarity: 'Uncommon', image: 'https://placehold.co/96x96', stock: 82 },
        { id: 'item-38', name: 'Crystalline Drum', rarity: 'Rare', image: 'https://placehold.co/96x96', stock: 29 },
        { id: 'item-39', name: 'Lucent Prism', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 6 },
        { id: 'item-40', name: 'Echo Tablet', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 18 },
      ],
      rarityCap: 3,
      auditLog: { enabled: false, channel: '#item-audit' },
    },
    boxes: {
      enabled: true,
      collection: [
        {
          id: 'box-1',
          name: 'Solar Crate',
          color: '#ff9b4a',
          price: 500,
          forSale: true,
          items: [
            { id: 'box-item-1', name: 'Solar Core', odds: 4, quantity: 1, rarity: 'Legendary' },
            { id: 'box-item-2', name: 'Photon Case', odds: 20, quantity: 4, rarity: 'Rare' },
          ],
        },
      ],
      behavior: {
        animationBackground: 'still',
        animationSpeed: 'standard',
        announceRare: false,
        announceChannel: '#rare-drops',
        logOpenings: true,
        stockLimited: false,
        forSaleOverride: true,
        openOnPurchase: true,
      },
    },
    marketplaceSuite: {
      enabled: true,
      resultsPerPage: 6,
      feesEnabled: true,
      feePercent: 6,
      appearance: {
        title: 'Marketplace',
        color: '#7c3aed',
      },
      trading: {
        enabled: true,
        giftingEnabled: true,
        tradeLogs: true,
        tradeChannel: '#trade-audit',
      },
      auctions: {
        enabled: true,
        resultsPerPage: 4,
        feeEnabled: true,
        feePercent: 6,
        buyoutsEnabled: true,
        appearance: {
          title: 'Auction House',
          color: '#f97316',
        },
        auctionLogs: true,
        auctionChannel: '#auction-logs',
      },
    },
    raffles: {
      enabled: true,
      activeLimit: 3,
      ticketPrice: 150,
      prizeMode: 'item',
      prizeName: 'Mythic Token',
      prizeQuantity: 1,
      durationDays: 1,
      scalingPot: false,
      prizePoolPercent: 60,
      logHistory: true,
      logChannel: '#raffle-history',
      active: [
        {
          id: 'raffle-lyra',
          name: 'Lyra Vault Key',
          ticketsSold: 212,
          closesIn: '4h 22m',
          creator: '@NovaOps',
          price: 150,
          prize: 'Mythic Token',
          prizeQuantity: 1,
          topBuyers: [
            { id: 'buyer-lyra-1', name: '@StarbornIris', tickets: 34 },
            { id: 'buyer-lyra-2', name: '@EchoHarbor', tickets: 28 },
            { id: 'buyer-lyra-3', name: '@NebulaTrace', tickets: 25 },
            { id: 'buyer-lyra-4', name: '@QuantumSable', tickets: 21 },
            { id: 'buyer-lyra-5', name: '@AuroraAxis', tickets: 18 },
          ],
        },
        {
          id: 'raffle-aurora',
          name: 'Aurora Relay Chest',
          ticketsSold: 68,
          closesIn: '11h 05m',
          creator: '@PrismHost',
          price: 150,
          prize: 'Aurora Cache',
          prizeQuantity: 3,
          topBuyers: [
            { id: 'buyer-aurora-1', name: '@LumenBard', tickets: 14 },
            { id: 'buyer-aurora-2', name: '@CascadeWing', tickets: 11 },
            { id: 'buyer-aurora-3', name: '@DriftBloom', tickets: 8 },
            { id: 'buyer-aurora-4', name: '@OrbitSpire', tickets: 6 },
            { id: 'buyer-aurora-5', name: '@GaleCircuit', tickets: 4 },
          ],
        },
      ],
    },
    boxBattles: {
      enabled: false,
    },
    serverShop: {
      name: 'Orbital Exchange',
      description: 'Rotating curated shop for prestige items.',
      itemMode: 'randomized',
      randomizedPool: [
        { id: 'pool-item-1', name: 'Nebula Blade', price: 1200, weight: 5, stock: 10 },
        { id: 'pool-item-2', name: 'Prism Core', price: 640, weight: 3, stock: null },
        { id: 'pool-item-3', name: 'Ion Nova Shard', price: 980, weight: 2, stock: 4 },
      ],
      schedule: [
        {
          id: 'schedule-day-1',
          date: '2024-07-15',
          slots: [
            { id: 'slot-1', label: 'Slot 1', itemName: 'Nebula Blade', price: 1200, stock: 5, featured: true },
            { id: 'slot-2', label: 'Slot 2', itemName: 'Prism Core', price: 600, stock: 12, featured: false },
          ],
        },
        {
          id: 'schedule-day-2',
          date: '2024-07-16',
          slots: [
            { id: 'slot-3', label: 'Slot 1', itemName: 'Ion Nova Shard', price: 980, stock: 8, featured: true },
            { id: 'slot-4', label: 'Slot 2', itemName: 'Cobalt Feather', price: 450, stock: 20, featured: false },
          ],
        },
      ],
      accentColor: '#0ea5e9',
      tomorrowVisibility: false,
      randomRotation: false,
      featuredHeroEnabled: false,
      backgroundStyle: 'default',
      layout: 'grid',
      limitedStock: false,
    },
    leaderboards: {
      enabled: true,
      currency: true,
      items: true,
      cadences: ['monthly', 'weekly'],
    },
    permissions: {
      adminRoles: ['@Admin', '@Staff'],
      blockedRoles: ['@Muted'],
      commandRestrictions: [],
    },
    auditLogs: {
      economy: true,
      items: true,
      shops: true,
      admin: true,
      trades: true,
      boxes: true,
    },
    auditLogChannels: {
      economy: '#economy-audit',
      items: '#items-audit',
      shops: '#shops-audit',
      admin: '#admin-audit',
      trades: '#trades-audit',
      boxes: '#boxes-audit',
    },
    billing: {
      plan: 'Creator',
      featureLocks: ['Mystery box animation', 'Premium streak profiles', 'Shop hero item'],
      perks: ['Concierge support', 'Unlimited boosters', 'Private roadmap'],
    },
    system: {
      language: 'English',
      timezone: 'UTC',
    },
  },
  featureFlags: FEATURE_FLAG_DEFAULTS,
};
