export const TOP_NAV_LINKS = [
  { label: 'Dashboard', to: '/app', end: true },
  { label: 'Docs', to: '/docs', end: true },
];

export const SIDEBAR_GROUPS = [
  {
    title: 'Control Center',
    items: [{ key: 'dashboard', label: 'Dashboard', icon: '🏠', path: '/app' }],
  },
  {
    title: 'Modules',
    items: [
      { key: 'guild-economy', label: 'Economy', icon: '💸', path: '/app/guild/economy' },
      { key: 'guild-items', label: 'Items & Boxes', icon: '🎁', path: '/app/guild/items' },
      { key: 'guild-market', label: 'Marketplace', icon: '🛍️', path: '/app/guild/marketplace' },
      { key: 'guild-raffles', label: 'Raffles & Battles', icon: '🎟️', path: '/app/guild/raffles' },
      { key: 'guild-shop', label: 'Server Shop', icon: '🏪', path: '/app/guild/shop' },
      { key: 'guild-leaderboards', label: 'Leaderboards', icon: '🏆', path: '/app/guild/leaderboards' },
      { key: 'guild-audit', label: 'Audit & Billing', icon: '🛡️', path: '/app/guild/audit' },
    ],
  },
];

export const FEATURE_SECTIONS = [
  { key: 'core', title: 'Core Features', description: 'XP engines, jobs, and marketplaces that drive your economy.' },
  { key: 'management', title: 'Server Management', description: 'Drops, raffles, and hype mechanics for every event.' },
  { key: 'utilities', title: 'Utilities', description: 'Premium tooling, leaderboards, and observability layers.' },
];

export const PRICING_PLANS = [
  {
    id: 'lite',
    name: 'Lite',
    monthly: 2.49,
    monthlyAfter: 4.99,
    yearly: 1.87,
    yearlyAfter: 3.74,
    badge: null,
    features: [
      { label: 'Economy + jobs modules', included: true },
      { label: 'Marketplace + raffles', included: true },
      { label: 'Basic audit logs', included: true },
      { label: 'Premium-only features', included: false },
      { label: 'Concierge support', included: false },
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    monthly: 3.99,
    monthlyAfter: 7.99,
    yearly: 2.99,
    yearlyAfter: 5.99,
    badge: 'Most Popular',
    features: [
      { label: 'Everything in Lite', included: true },
      { label: 'Premium-only features 👑', included: true },
      { label: 'Advanced analytics', included: true },
      { label: 'Concierge support', included: false },
    ],
  },
  {
    id: 'ultra',
    name: 'Ultra',
    monthly: 7.99,
    monthlyAfter: 15.99,
    yearly: 5.99,
    yearlyAfter: 11.99,
    badge: null,
    features: [
      { label: 'Everything in Premium', included: true },
      { label: 'Concierge support', included: true },
      { label: 'Custom branding', included: true },
      { label: '24/7 ops bridge', included: true },
    ],
  },
];

export const PLAN_COMPARISON = [
  { feature: 'Economy + Jobs', tiers: { free: true, lite: true, premium: true, ultra: true } },
  { feature: 'Marketplace + Raffles', tiers: { free: false, lite: true, premium: true, ultra: true } },
  { feature: 'Premium-only commands', tiers: { free: false, lite: false, premium: true, ultra: true } },
  { feature: 'Concierge support', tiers: { free: false, lite: false, premium: false, ultra: true } },
  { feature: 'Custom branding', tiers: { free: false, lite: false, premium: true, ultra: true } },
];

export const COMMAND_GROUPS = [
  {
    title: 'Economy & Transfers',
    description: 'Core balance management commands for your in-server economy.',
    commands: ['/trade', '/gift', '/add-money', '/remove-money', '/balance', '/daily', '/work', '/<currency>-leaderboard'],
  },
  {
    title: 'Items & Inventory',
    description: 'Create, edit, and inspect virtual goods members can equip.',
    commands: ['/create-item', '/edit-item', '/view-item', '/remove-item', '/add-item', '/inventory', '/item-leaderboard'],
  },
  {
    title: 'Shops & Marketplace',
    description: 'Sell goods in user shops or server-wide storefronts.',
    commands: ['/marketplace', '/user-shop', '/serverwide-shop-view', '/serverwide-shop-edit', '/serverwide-shop-buy', '/test-shop'],
  },
  {
    title: 'Auctions & Raffles',
    description: 'High-stakes raffles and live auction house bidding.',
    commands: ['/auction-house-add', '/auction-house-bid', '/auction-house-view', '/create-raffle', '/buy-tickets'],
  },
  {
    title: 'Mystery Boxes & Battles',
    description: 'Hype-driven boxes, battles, and related flows.',
    commands: ['/create-mystery-box', '/edit-mystery-box', '/view-mystery-boxes', '/buy-mystery-box', '/open-mystery-box', '/box-battles'],
  },
  {
    title: 'Announcements',
    description: 'Keep members looped in about drops and events.',
    commands: ['/notifications'],
  },
];

export const FEATURE_MODULES = [
  {
    key: 'economy',
    title: 'Economy Engine',
    description: 'Tune payouts, taxes, and cooldowns to shape your currency loops.',
    icon: '💸',
    category: 'core',
    premium: false,
    route: '/app/economy',
    pill: 'Core',
    defaultEnabled: true,
    modes: ['balanced', 'aggressive', 'chill'],
  },
  {
    key: 'jobs',
    title: 'Jobs Board',
    description: 'Stackable contracts with difficulty tiers, rerolls, and streak logic.',
    icon: '🛠️',
    category: 'core',
    premium: false,
    route: '/app/jobs',
    pill: 'Automation',
    defaultEnabled: true,
    modes: ['standard', 'hardcore', 'cozy'],
  },
  {
    key: 'marketplace',
    title: 'Marketplace',
    description: 'Let members trade cosmetics, boosts, and creator drops safely.',
    icon: '🛍️',
    category: 'core',
    premium: false,
    route: '/app/marketplace',
    pill: 'Commerce',
    defaultEnabled: true,
    modes: ['curated', 'open', 'seasonal'],
  },
  {
    key: 'serverwideStore',
    title: 'Serverwide Store',
    description: 'Curate server-operated storefronts with limited drops and global inventory controls.',
    icon: '🏪',
    category: 'core',
    premium: false,
    route: '/app/marketplace',
    pill: 'Commerce',
    defaultEnabled: true,
    modes: ['standard', 'limited', 'event'],
  },
  {
    key: 'mysteryBoxes',
    title: 'Mystery Boxes',
    description: 'Create fully custom mystery boxes with rewards, rarities, and exciting randomized openings.',
    icon: '🎁',
    category: 'management',
    premium: false,
    route: '/app/mystery-boxes',
    pill: 'Events',
    defaultEnabled: false,
    modes: ['cinematic', 'arcade', 'minimal'],
  },
  {
    key: 'raffles',
    title: 'Raffles',
    description: 'Ticket-based giveaways with verification and multi-winner draws.',
    icon: '🎟️',
    category: 'management',
    premium: false,
    route: '/app/raffles',
    pill: 'Engagement',
    defaultEnabled: true,
    modes: ['verification', 'open'],
  },
  {
    key: 'leaderboards',
    title: 'Leaderboards',
    description: 'Seasonal ranked ladders with trophy roles and automated resets.',
    icon: '🏆',
    category: 'utilities',
    premium: true,
    route: '/app/leaderboards',
    pill: 'Premium',
    defaultEnabled: true,
    modes: ['seasonal', 'lifetime'],
  },
  {
    key: 'premium',
    title: 'Premium Hub',
    description: 'AI insights, concierge support, and branding overrides for top guilds.',
    icon: '💎',
    category: 'utilities',
    premium: true,
    route: '/app/premium',
    pill: 'Upgrade',
    defaultEnabled: true,
    modes: ['ai', 'concierge'],
  },
  {
    key: 'logs',
    title: 'Audit Logs',
    description: 'Live stream of bot actions with retention controls and alerts.',
    icon: '📜',
    category: 'utilities',
    premium: false,
    route: '/app/logs',
    pill: 'Visibility',
    defaultEnabled: true,
    modes: ['compressed', 'verbose'],
  },
  {
    key: 'settings',
    title: 'Server Settings',
    description: 'Maintenance windows, beta access, and timezone alignment.',
    icon: '⚙️',
    category: 'utilities',
    premium: false,
    route: '/app/settings',
    pill: 'Admin',
    defaultEnabled: true,
    modes: ['auto', 'manual'],
  },
];

export const FEATURE_FLAG_DEFAULTS = FEATURE_MODULES.reduce((acc, module) => {
  acc[module.key] = {
    enabled: module.defaultEnabled ?? false,
    mode: module.modes?.[0] ?? 'auto',
  };
  return acc;
}, {});

export const MOCK_USER = {
  id: 'plixi-admin',
  username: 'Ari Rhythm',
  discriminator: '1024',
  avatar: 'https://i.pravatar.cc/80?img=47',
  banner: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=60',
  planTier: 'Creator',
};

export const MOCK_GUILDS = [
  {
    id: 'guild-starlance',
    name: 'Starlance Collective',
    icon: '🌌',
    memberCount: 128402,
    premium: true,
    vanity: 'starlance.gg',
  },
  {
    id: 'guild-synth',
    name: 'Synth District',
    icon: '🎛️',
    memberCount: 74218,
    premium: false,
    vanity: 'discord.gg/synth',
  },
  {
    id: 'guild-harbor',
    name: 'Harbor Operators',
    icon: '⚓',
    memberCount: 22451,
    premium: false,
    vanity: 'plixi.gg/harbor',
  },
];

export const DEFAULT_SETTINGS = {
  economy: {
    economyEnabled: true,
    currencyName: 'Credits',
    startingBalance: 250,
    decimalsEnabled: false,
    dailyRewardsEnabled: true,
    dailyBaseAmount: 200,
    dailyRoleRewards: [
      { id: 'role-vip', role: '@VIP', amount: 350 },
      { id: 'role-booster', role: '@Booster', amount: 500 },
    ],
    dailyCooldownHours: 24,
    streaksEnabled: true,
    streakBonusMultiplier: 1.25,
    workEnabled: true,
    workCooldownMinutes: 45,
    workPayMin: 120,
    workPayMax: 320,
  },
  jobs: {
    jobsEnabled: true,
    jobDifficulty: 'standard',
    shiftLength: 4,
    payoutMultiplier: 1.2,
    rerollCost: 150,
    autoAssign: true,
  },
  marketplace: {
    marketplaceEnabled: true,
    allowUserListings: true,
    listingFee: 4,
    featuredSlots: 3,
    currencyName: 'Credits',
    premiumAnalytics: true,
  },
  mysteryBoxes: {
    boxesEnabled: true,
    legendaryRate: 3,
    animationStyle: 'nebula',
    guaranteedDrops: false,
  },
  raffles: {
    rafflesEnabled: true,
    maxTickets: 120,
    requireVerification: true,
    notifyWinners: true,
    autoClaim: false,
  },
  premium: {
    aiInsights: true,
    brandingControl: true,
    concierge: false,
  },
  logs: {
    logRetentionDays: 14,
    streamingChannels: ['#plixi-audit'],
    alertOnFailures: true,
    maskSensitive: true,
  },
  leaderboards: {
    leaderboardsEnabled: true,
    rotation: 'monthly',
    rewardRole: 'Top 10',
    celebrateWithEmbeds: true,
  },
  settings: {
    maintenanceMode: false,
    timezone: 'UTC',
    allowBeta: true,
  },
  guild: {
    currency: {
      name: 'Credits',
      startingBalance: 250,
      decimalsEnabled: false,
      auditLog: { enabled: false, channel: '#currency-audit' },
    },
    daily: {
      enabled: true,
      baseAmount: 200,
      cooldownHours: 24,
      roleAmounts: [
        { id: 'vip', role: '@VIP', amount: 320 },
        { id: 'vip-plus', role: '@VIP+', amount: 450 },
      ],
      streak: {
        enabled: true,
        profile: 'regular',
        multiplier: 1.3,
      },
    },
    work: {
      enabled: true,
      cooldownMinutes: 45,
      payMin: 120,
      payMax: 320,
      jobs: [
        { id: 'job-1', name: 'Nebula Courier' },
        { id: 'job-2', name: 'Quantum Analyst' },
        { id: 'job-3', name: 'Forge Tech' },
      ],
    },
    items: {
      catalog: [
        { id: 'item-1', name: 'Starlance Badge', rarity: 'Epic', image: 'https://placehold.co/96x96', stock: 25 },
        { id: 'item-2', name: 'Nebula Cape', rarity: 'Legendary', image: 'https://placehold.co/96x96', stock: 5 },
      ],
      rarityCap: 3,
      auditLog: { enabled: false, channel: '#item-audit' },
    },
    boxes: {
      enabled: true,
      collection: [
        {
          id: 'box-1',
          name: 'Solar Crate',
          color: '#ff9b4a',
          price: 500,
          forSale: true,
          items: [
            { id: 'box-item-1', name: 'Solar Core', odds: 4 },
            { id: 'box-item-2', name: 'Photon Case', odds: 20 },
          ],
        },
      ],
      behavior: {
        animationBackground: 'still',
        animationSpeed: 'standard',
        announceRare: false,
        announceChannel: '#rare-drops',
        logOpenings: true,
        stockLimited: false,
        forSaleOverride: true,
      },
    },
    marketplaceSuite: {
      enabled: true,
      resultsPerPage: 6,
      feesEnabled: true,
      feePercent: 6,
      trading: {
        enabled: true,
        giftingEnabled: true,
        tradeLogs: true,
        tradeChannel: '#trade-audit',
      },
      auctions: {
        enabled: true,
        feeEnabled: true,
        auctionLogs: true,
        auctionChannel: '#auction-logs',
      },
    },
    raffles: {
      activeLimit: 3,
      ticketPrice: 150,
      prizeMode: 'item',
      prizeName: 'Mythic Token',
      durationDays: 1,
      scalingPot: false,
      prizePoolPercent: 60,
      logHistory: true,
      logChannel: '#raffle-history',
    },
    boxBattles: {
      enabled: false,
    },
    serverShop: {
      name: 'Orbital Exchange',
      description: 'Rotating curated shop for prestige items.',
      items: [
        { id: 'shop-item-1', name: 'Nebula Blade', price: 1200, featured: true },
        { id: 'shop-item-2', name: 'Prism Core', price: 640, featured: false },
      ],
      tomorrowVisibility: false,
      randomRotation: false,
      featuredHeroEnabled: false,
      backgroundStyle: 'default',
      layout: 'grid',
      limitedStock: false,
    },
    leaderboards: {
      enabled: true,
      currency: true,
      items: true,
      cadences: ['monthly', 'weekly'],
    },
    permissions: {
      adminRoles: ['@Admin', '@Staff'],
      blockedRoles: ['@Muted'],
      commandRestrictions: [],
    },
    auditLogs: {
      economy: true,
      items: true,
      shops: true,
      admin: true,
      trades: true,
      boxes: true,
    },
    billing: {
      plan: 'Creator',
      featureLocks: ['Mystery box animation', 'Premium streak profiles', 'Shop hero item'],
      perks: ['Concierge support', 'Unlimited boosters', 'Private roadmap'],
    },
    system: {
      language: 'English',
      timezone: 'UTC',
    },
  },
  featureFlags: FEATURE_FLAG_DEFAULTS,
};
